//------------------------------------------------------------------------------
// \<auto-generated>
//     This code was generated by a tool.
//
// \</auto-generated>
//------------------------------------------------------------------------------

namespace ArgHolidays
{
    public partial class Error
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Error));
            txtError = new System.Windows.Forms.TextBox();
            lnkCopyToClipboard = new System.Windows.Forms.LinkLabel();
            btnOk = new System.Windows.Forms.Button();
            SuspendLayout();
            // 
            // txtError
            // 
            txtError.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            txtError.BackColor = System.Drawing.SystemColors.Window;
            txtError.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            txtError.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            txtError.Location = new System.Drawing.Point(0, 0);
            txtError.Multiline = true;
            txtError.Name = "txtError";
            txtError.ReadOnly = true;
            txtError.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            txtError.Size = new System.Drawing.Size(635, 269);
            txtError.TabIndex = 0;
            txtError.WordWrap = false;
            // 
            // lnkCopyToClipboard
            // 
            lnkCopyToClipboard.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            lnkCopyToClipboard.AutoSize = true;
            lnkCopyToClipboard.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            lnkCopyToClipboard.LinkColor = System.Drawing.Color.DarkSlateBlue;
            lnkCopyToClipboard.Location = new System.Drawing.Point(-1, 272);
            lnkCopyToClipboard.Name = "lnkCopyToClipboard";
            lnkCopyToClipboard.Size = new System.Drawing.Size(114, 17);
            lnkCopyToClipboard.TabIndex = 1;
            lnkCopyToClipboard.TabStop = true;
            lnkCopyToClipboard.Text = "Copy to clipboard";
            lnkCopyToClipboard.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(LnkCopyToClipboard_LinkClicked);
            // 
            // btnOk
            // 
            btnOk.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            btnOk.DialogResult = System.Windows.Forms.DialogResult.OK;
            btnOk.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            btnOk.Location = new System.Drawing.Point(550, 281);
            btnOk.Name = "btnOk";
            btnOk.Size = new System.Drawing.Size(75, 23);
            btnOk.TabIndex = 2;
            btnOk.Text = "Ok";
            btnOk.UseVisualStyleBackColor = true;
            // 
            // Error
            // 
            AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            BackColor = System.Drawing.SystemColors.Control;
            ClientSize = new System.Drawing.Size(635, 314);
            Controls.Add(btnOk);
            Controls.Add(lnkCopyToClipboard);
            Controls.Add(txtError);
            Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            Icon = ((System.Drawing.Icon)(resources.GetObject("$Icon")));
            MinimizeBox = false;
            Name = "Error";
            ShowInTaskbar = false;
            StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            Text = "Something Went Wrong";
            ResumeLayout(false);
            PerformLayout();

        }

        #endregion

        private System.Windows.Forms.TextBox txtError;
        private System.Windows.Forms.LinkLabel lnkCopyToClipboard;
        private System.Windows.Forms.Button btnOk;
    }
}